name: lint-test

on:
  push:
    branches: [ "dev", "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install poetry
          poetry install
          poetry run flake8
